---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - math.ymktmk.github.io
  resources:
  - numbers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.ymktmk.github.io
  resources:
  - numbers/finalizers
  verbs:
  - update
- apiGroups:
  - math.ymktmk.github.io
  resources:
  - numbers/status
  verbs:
  - get
  - patch
  - update
