apiVersion: math.ymktmk.github.io/v1beta1
kind: Number
metadata:
  name: number-sample
spec:
  value: 225

# Test用(全然関係ない)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
