on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/ymktmk/math-controller
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ymktmk
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
