on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Build Push Release
    if: startsWith( github.ref, 'refs/tags/' )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Create release YAML (math-controller.yaml)
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          IMAGE_ID=$REGISTRY/$IMAGE_NAME
          make manifests-release IMG=$IMAGE_ID:$VERSION
      
      - name: Publish images to the registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            $REGISTRY/$IMAGE_NAME:latest
            $REGISTRY/$IMAGE_NAME:$VERSION
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get_version.outputs.TAG_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: math-controller.yaml
